[package]
name = "mpd_client"
version = "0.0.1"
authors = ["Ole Bertram <git@bertr.am>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpd_protocol = "0.4.0"
tokio = { version = "0.2.11", features = ["full"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
futures = "0.3.4"
